# Generated by Django 4.2.7 on 2023-12-29 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('FoodID', models.AutoField(primary_key=True, serialize=False)),
                ('FoodName', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IsAvailable', models.BooleanField(default=True)),
                ('Image', models.ImageField(upload_to='food_images/')),
                ('VarietyOptions', models.CharField(max_length=255)),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('OrderDate', models.DateTimeField(auto_now_add=True)),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='registerDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('OrderItemID', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.PositiveIntegerField()),
                ('Subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FoodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.food')),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
