# Generated by Django 4.2.7 on 2024-03-15 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_category_categoryname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='CategoryID',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='CategoryName',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='registerDate',
            new_name='register_date',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='CategoryID',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='FoodID',
            new_name='food_id',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='FoodName',
            new_name='food_name',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='IsAvailable',
            new_name='is_available',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='VarietyOptions',
            new_name='variety_options',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='OrderDate',
            new_name='order_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='OrderID',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='TotalAmount',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='UserID',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='FoodID',
            new_name='food_id',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='OrderID',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='OrderItemID',
            new_name='order_item_id',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='Quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='Subtotal',
            new_name='subtotal',
        ),
    ]
